// This mock data simulates the response from Spoonacular's /recipes/complexSearch endpoint
// Use this to avoid hitting the daily limit during UI development.

export const MOCK_RECIPES = {
  results: [
    {
      id: 716429,
      title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
      image: "https://img.spoonacular.com/recipes/716429-312x231.jpg",
      imageType: "jpg",
      summary: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be just the main course you are searching for.",
      cuisines: ["Italian"],
      dishTypes: ["lunch", "main course"],
      diets: ["vegetarian"],
      readyInMinutes: 45,
      servings: 4,
      popularity: 85,
      healthiness: 70,
      price: 1.50,
      calories: 450,
      protein: 15,
    },
    {
      id: 715538,
      title: "Bruschetta Style Pork & Pasta",
      image: "https://img.spoonacular.com/recipes/715538-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Italian"],
      dishTypes: ["main course"],
      diets: [],
      readyInMinutes: 35,
      servings: 2,
      popularity: 78,
      healthiness: 55,
      price: 2.20,
      calories: 600,
      protein: 25,
    },
    {
      id: 646512,
      title: "Salmon with roasted vegetables",
      image: "https://img.spoonacular.com/recipes/646512-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Mediterranean"],
      diets: ["gluten free", "dairy free", "pescatarian"],
      readyInMinutes: 45,
      servings: 2,
      popularity: 90,
      healthiness: 92,
      price: 4.80,
      calories: 400,
      protein: 35,
    },
    {
      id: 654959,
      title: "Pasta With Tuna",
      image: "https://img.spoonacular.com/recipes/654959-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Italian"],
      diets: ["pescatarian"],
      readyInMinutes: 20,
      servings: 4,
      popularity: 65,
      healthiness: 60,
      price: 1.80,
      calories: 550,
      protein: 20,
    },
    {
      id: 633033,
      title: "Asian Thyme Chicken",
      image: "https://img.spoonacular.com/recipes/633033-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Asian"],
      diets: ["gluten free", "dairy free"],
      readyInMinutes: 45,
      servings: 4,
      popularity: 80,
      healthiness: 75,
      price: 3.00,
      calories: 480,
      protein: 30,
    },
    {
      id: 644387,
      title: "Garlicky Kale",
      image: "https://img.spoonacular.com/recipes/644387-312x231.jpg",
      imageType: "jpg",
      cuisines: ["American"],
      diets: ["vegan", "gluten free", "dairy free"],
      readyInMinutes: 15,
      servings: 2,
      popularity: 70,
      healthiness: 88,
      price: 1.20,
      calories: 200,
      protein: 8,
    },
    {
      id: 716268,
      title: "African Chicken Peanut Stew",
      image: "https://img.spoonacular.com/recipes/716268-312x231.jpg",
      imageType: "jpg",
      cuisines: ["African"],
      diets: ["gluten free", "dairy free"],
      readyInMinutes: 45,
      servings: 1,
      popularity: 60,
      healthiness: 72,
      price: 3.50,
      calories: 500,
      protein: 30,
    },
    {
      id: 663050,
      title: "Thai Vegetable Curry",
      image: "https://img.spoonacular.com/recipes/663050-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Thai"],
      diets: ["vegan", "gluten free"],
      readyInMinutes: 30,
      servings: 4,
      popularity: 82,
      healthiness: 80,
      price: 2.00,
      calories: 380,
      protein: 10,
    },
    {
      id: 661447,
      title: "Stuffed Sticky Rice Balls",
      image: "https://img.spoonacular.com/recipes/661447-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Chinese", "Asian"],
      diets: ["gluten free", "vegetarian"],
      readyInMinutes: 60,
      servings: 6,
      popularity: 50,
      healthiness: 65,
      price: 1.00,
      calories: 300,
      protein: 5,
    },
    {
      id: 640062,
      title: "Corn-Fritters with Chili-Lime-Mayo",
      image: "https://img.spoonacular.com/recipes/640062-312x231.jpg",
      imageType: "jpg",
      cuisines: ["American"],
      diets: ["vegetarian"],
      readyInMinutes: 30,
      servings: 4,
      popularity: 75,
      healthiness: 50,
      price: 1.75,
      calories: 320,
      protein: 7,
    },
    {
      id: 642582,
      title: "Farfalle with Peas, Ham and Cream",
      image: "https://img.spoonacular.com/recipes/642582-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Italian"],
      diets: [],
      readyInMinutes: 30,
      servings: 4,
      popularity: 70,
      healthiness: 45,
      price: 2.50,
      calories: 650,
      protein: 22,
    },
    {
      id: 652423,
      title: "Moroccan Chickpea and Lentil Stew",
      image: "https://img.spoonacular.com/recipes/652423-312x231.jpg",
      imageType: "jpg",
      cuisines: ["African", "Moroccan"],
      diets: ["vegan", "gluten free"],
      readyInMinutes: 45,
      servings: 4,
      popularity: 88,
      healthiness: 90,
      price: 2.10,
      calories: 350,
      protein: 18,
    },
    {
      id: 639413,
      title: "Classic Beef Tacos",
      image: "https://img.spoonacular.com/recipes/639413-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Mexican"],
      diets: [],
      readyInMinutes: 25,
      servings: 4,
      popularity: 92,
      healthiness: 68,
      price: 2.80,
      calories: 580,
      protein: 28,
    },
    {
      id: 641908,
      title: "Easy Chicken Enchiladas",
      image: "https://img.spoonacular.com/recipes/641908-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Mexican"],
      diets: ["gluten free"],
      readyInMinutes: 40,
      servings: 4,
      popularity: 89,
      healthiness: 60,
      price: 3.20,
      calories: 620,
      protein: 32,
    },
    {
      id: 651977,
      title: "Miso Glazed Salmon",
      image: "https://img.spoonacular.com/recipes/651977-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Japanese", "Asian"],
      diets: ["pescatarian", "gluten free", "dairy free"],
      readyInMinutes: 20,
      servings: 2,
      popularity: 91,
      healthiness: 95,
      price: 5.00,
      calories: 420,
      protein: 38,
    },
    {
      id: 660228,
      title: "Slow Cooker Beef Stew",
      image: "https://img.spoonacular.com/recipes/660228-312x231.jpg",
      imageType: "jpg",
      cuisines: ["American", "European"],
      diets: ["gluten free"],
      readyInMinutes: 480,
      servings: 6,
      popularity: 84,
      healthiness: 70,
      price: 2.70,
      calories: 530,
      protein: 30,
    },
    {
      id: 648431,
      title: "Japanese Curry",
      image: "https://img.spoonacular.com/recipes/648431-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Japanese", "Asian"],
      diets: ["dairy free"],
      readyInMinutes: 45,
      servings: 4,
      popularity: 76,
      healthiness: 62,
      price: 2.40,
      calories: 490,
      protein: 18,
    },
    {
      id: 637161,
      title: "Cashew Chicken",
      image: "https://img.spoonacular.com/recipes/637161-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Chinese", "Asian"],
      diets: ["dairy free"],
      readyInMinutes: 30,
      servings: 3,
      popularity: 87,
      healthiness: 78,
      price: 3.10,
      calories: 510,
      protein: 28,
    },
    {
      id: 649114,
      title: "Lemon Herb Roasted Chicken",
      image: "https://img.spoonacular.com/recipes/649114-312x231.jpg",
      imageType: "jpg",
      cuisines: ["European", "American"],
      diets: ["gluten free", "dairy free"],
      readyInMinutes: 75,
      servings: 4,
      popularity: 83,
      healthiness: 85,
      price: 3.80,
      calories: 470,
      protein: 35,
    },
    {
      id: 638035,
      title: "Chicken Tikka Masala",
      image: "https://img.spoonacular.com/recipes/638035-312x231.jpg",
      imageType: "jpg",
      cuisines: ["Indian", "Asian"],
      diets: ["gluten free"],
      readyInMinutes: 45,
      servings: 4,
      popularity: 95,
      healthiness: 70,
      price: 3.90,
      calories: 600,
      protein: 40,
    }
  ],
  offset: 0,
  number: 20,
  totalResults: 20,
};

export const POPULAR_CUISINES = [
  { name: "Italian", image: "https://images.unsplash.com/photo-1498579150354-977475b7ea0b?auto=format&fit=crop&w=800&q=80" },
  { name: "Mexican", image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80" },
  { name: "Asian", image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80" },
  { name: "American", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80" },
  { name: "European", image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80" },
  { name: "Indian", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80" },
  { name: "Mediterranean", image: "https://images.unsplash.com/photo-1544124499-58912cbddaad?auto=format&fit=crop&w=800&q=80" },
  { name: "French", image: "https://images.unsplash.com/photo-1550950158-d0d960dff51b?auto=format&fit=crop&w=800&q=80" },
  { name: "Japanese", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80" },
  { name: "Thai", image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=800&q=80" },
  { name: "Spanish", image: "https://images.pexels.com/photos/1527603/pexels-photo-1527603.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { name: "Eastern Europe", image: "https://www.shutterstock.com/image-photo/slovak-national-dish-bryndzove-halusky-600nw-1921788164.jpg" },
];